<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MsgImageExtractor</AssemblyName>
    <RootNamespace>MsgImageExtractor</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MsgReader" Version="6.*" />
  </ItemGroup>

</Project>
